site_name: cs_syq_wiki

nav:
  - 主页:
      - 这是什么?: "index.md"
  - 关于:
      - 我们的初衷: "关于/目标.md"
      - 联系我们: "关于/联系我们.md"
  - 选课:
      - 导航: "选课/index.md"
      - 数字电路: "选课/数字电路.md"
      - 组成原理: "选课/组成原理.md"
      - 操作系统: "选课/操作系统.md"
      - 网络: "选课/网络.md"
  - 资源汇总:
      - 可能会对你有用的网站: "资源汇总/网站.md"
      - 我该如何发育？: "资源汇总/发育路线.md"
      - 一名高素质的程序员应该是什么样子: "资源汇总/程序员.md"
  - 竞赛:
      - xcpc: "竞赛/acm-icpc.md"
  - 科研:
      - 总览: "科研/index.md"
      - 方向:
        - 你需要知道的方向: "科研/方向/index.md"
        - 体系结构: "科研/方向/体系结构.md"
        - 软件工程: "科研/方向/软件工程.md"
        - 数据库: "科研/方向/数据库.md"
        - 网络与信息安全: "科研/方向/网络与信息安全.md"
        - AI: "科研/方向/AI.md"
        - TCS: "科研/方向/TCS.md"
        - 交叉与其他: "科研/方向/交叉与其他.md"
      - 如何获得科研实习: "科研/科研实习.md"
  - 工具:
    - Vim: "工具/Vim.md"


theme:
  name: 'material'
